apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-api002
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank-api002
  template:
    metadata:
      labels:
        app: bank-api002
    spec:
      containers:
        - name: bank-api002
          image: ajvideira/bank-api
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: bank-api-secret002
          volumeMounts:
            - name: bank-api-volume002
              mountPath: /home/node/app/.env
              subPath: .env

      volumes:
        - name: bank-api-volume002
          configMap:
            name: bank-api-conf002
            items:
              - key: env
                path: .env
